apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: amini5454@gmail.com
    privateKeySecretRef:
      name: acme-prod
    solvers:
    - dns01:
        azureDNS:
          resourceGroupName: rg-imdbgraph-prod
          subscriptionID: xxx
          hostedZoneName: api.imdbgraph.org
          environment: AzurePublicCloud
          managedIdentity:
            clientID: xxx