FROM httpd:2.4
COPY ./my-httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./imdbgraph.org.conf /usr/local/apache2/conf/imdbgraph.org.conf
COPY ./imdbgraph.org-le-ssl.conf /usr/local/apache2/conf/imdbgraph.org-le-ssl.conf