variables:
  POSTGRES_DB: 'test_db'
  POSTGRES_USER: 'test_user'
  POSTGRES_PASSWORD: "$DB_PASSWORD"
  POSTGRES_HOST_AUTH_METHOD: 'trust'

  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache downloaded dependencies and plugins between builds.
cache:
  paths:
    - .m2/repository

stages:
  - build
  - test

build-containers:
  stage: build
  image: docker:20.10.5
  services:
    - docker:20.10.5-dind

  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - apk update
    - apk upgrade
    - apk add --no-cache docker-compose
    # Secure practice for passing password: https://stackoverflow.com/a/51518255/6310030
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    # https://docs.gitlab.com/ee/user/packages/container_registry/#container-registry-examples-with-gitlab-cicd
    - docker-compose --version
    - docker-compose build database
    - docker-compose push database

integration-tests:
  stage: test
  image: maven:3.6.3-openjdk-16

  # Postgres database required for integration testing
  services:
    - name: "$CI_REGISTRY_IMAGE/database:$CI_COMMIT_REF_SLUG"
      alias: postgres

  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
