apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - routes.yaml
configMapGenerator:
  - name: imdbgraph-config
    files:
      - .env
secretGenerator:
  - name: imdbgraph-secrets
    envs:
    - .env.secret