apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: imdbgraph
resources:
  - deployment.yaml
configMapGenerator:
  - name: imdbgraph-config
    files:
      - .env
secretGenerator:
  - name: secrets
    envs:
      - .env.secret