apiVersion: v1
kind: Service
metadata:
  name: imdbgraph-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: imdbgraph-api
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: imdbgraph-http
spec:
  parentRefs:
  - name: traefik
    namespace: networking
    kind: Gateway
  hostnames:
  - api.staging.imdbgraph.org
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: imdbgraph-https
spec:
  parentRefs:
  - name: traefik
    namespace: networking
    kind: Gateway
  hostnames:
  - api.staging.imdbgraph.org
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: imdbgraph-service
      namespace: imdbgraph
      port: 80