apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  annotations:
    azure.workload.identity/client-id: a9147680-f4df-46bc-84d8-a63a4ebbf5ca
    azure.workload.identity/tenant-id: 1eb98549-3952-4fc7-b783-da109d29a89a
