apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imdbgraph-tls
  namespace: cert-manager
spec:
  secretName: imdbgraph-tls
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - imdbgraph.org
