apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imdbgraph-tls
  namespace: default
spec:
  dnsNames:
    - api.staging.imdbgraph.org
  secretName: imdbgraph-tls
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt
    kind: Issuer
    group: cert-manager.io