---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: imdbgraph-secrets
  namespace: imdbgraph
spec:
  encryptedData:
    DATABASE_PASSWORD: AgAFGSgszqAKC+5xGv7S20akRawNL0mUk7+d6GK5l5+O5v0bGgmLIJapn9L9DbSG77M0DqUuXWchQDm61QquJnV/lgQGQTGpsqCbDWoeCjsGA4hDfwaOR31cY/X20c/n7smpsvPIFQLCqBdyP/tZKASTx3+rNtz6hFbnoKLao+zQncgK1cqGBw8uX67x6u6jHyYmGCAAK2ojnGLQOA+oYTXjfxwJx6DTN/V+L6EbTprFcgJ86mmQosXM9GtJU/AQB2uI5xY1AP1YZ3qYtHBXSglwAx9g6pKCcXBF3yZ+9rOCyA38G9YK8CZUPSUSNd2fTUC0ANPU7vygzdq9/ejHyKIhTVk1DLOvsQ0DouapesCDTRY73n4r3JRyzf6NYyp9wq2Splxm7GfQoeLSWaFbm/FpVRur6dexwrFfhXYyRH1ke6ZKkar1GAWJOQ9tSlCv6XMHc03585SkSVBACV8xlIk3qDb1R4zq2fIqpcfxY4z/sLYpjExq2yfY08wmRN9GkoMar4OxQ1QQHTIidM4N2PUtOmFQ9+5JwXqthYg+2fFmop3QUC3mrdKpKXONrotsL8xnEdAznj8WEFb9EFtjebrFyVNkYG1FTAJILQVqQccoo+GVDHymHSh29sp2cyqDsA4UbaW24VvqKgguGl65Fq5acXhrsDqIkoueWvvEMszYTYeC3CWepRnSNJMRaQSGzIv5cHZPL3cvEQ==
    OMDB_KEY: AgCXAKqi/cpA4s/FIImUeV9YMsFVC3ZJTvRwgQouF+DRKrEJRPWLx+Rkg+xQI9EY1eJXxfA+Z8trZlULK05DSYPzLHjbpl/uxt7J0uLvHVBQgF5o3/xl3abZbyIYFg7Hn3JMz5djfCNe7KC1IZVj8eauHm1c4h3Ll4YJNlOQ0T2+OYaxGQlSpJq8twEEdcwMg+yyGR+4iOMA215vScE8lV4lWkBcXIlZiTy/13AGdJHpcIhqEkCn2W2YEEnKQwwC/S4/Ve7FJQvlcCOiZCg2pnjadVYV6lOyTmS38op51fxz5T2aoy/jgmqEf6hEMidOHNvTsDQCgU5a17kalfARL6eli8vHr8VU/IipQMi26f8pATvo+ccq7iNk692PNMe/sc63qCeoq9O1QaDtfPEloGiPZixeMD8pGV3AHDrvb5J+Tk2HcSoufMDPb0skYdowgrYDfspDX9HKYqrnu4JBNqD6+EXnzASPniGtJwLpgFTYMoTBVUlYzbRuCtKzvTji1g4iwWkvjf5BKFsv6fg46zBqP+jYiaT+faeVIWkOsJibkkmCAQxyIM59oxuaQvCfmm04u+KM9QvEALhq8vE4pBYWrxBeNOxCKntliLpLIFdliG0J1afELxG2hVerItqQKfklf+g2oWcTGUCfJ/dsha3hHoNQAqOWZeZjoUYSqBUBpyu0Qq6DsSDARc6+VNhDc7e0Y9FbAFMnvA==
  template:
    metadata:
      creationTimestamp: null
      name: imdbgraph-secrets
      namespace: imdbgraph
