---
apiVersion: v1
kind: Namespace
metadata:
  name: azure-load-balancer
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: azure-load-balancer
  namespace: azure-alb-system
spec:
  interval: 10m0s
  url: oci://mcr.microsoft.com/application-lb/charts/alb-controller
  ref:
    tag: "1.5.2"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: azure-load-balancer
  namespace: azure-alb-system
spec:
  interval: 10m0s
  timeout: 2m0s
  chartRef:
    kind: OCIRepository
    name: azure-load-balancer
  values:
    albController:
      namespace: azure-alb-system
      podIdentity:
        clientID: fc12067d-a639-4226-8725-6f675f941157
