---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mcr-alb-controller
  namespace: flux-system
spec:
  type: oci
  url: oci://mcr.microsoft.com/application-lb/charts
  interval: 10m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alb-controller
  namespace: azure-alb-system
spec:
  targetNamespace: azure-alb-system  # same as .metadata.namespace
  interval: 5m0s
  chart:
    spec:
      chart: alb-controller
      version: 1.5.2
      sourceRef:
        kind: HelmRepository
        name: mcr-alb-controller
        namespace: flux-system
  values:
    albController:
      namespace: azure-alb-system
      podIdentity:
        clientID: fc12067d-a639-4226-8725-6f675f941157
