- name: Install latest version of NGINX
  become: true
  apt:
    name: nginx
    state: latest
    update_cache: true

- name: Start NGINX service
  become: true
  service:
    name: nginx
    state: started
    enabled: true