- name: Install Required Packages
  become: true
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - acl
      - python3-psycopg2
    state: latest

- name: Start postgres service
  service:
    name: postgresql
    state: started
    enabled: true

- name: Create app database
  postgresql_db:
    state: present
    name: "{{ lookup('env', 'POSTGRES_DB' }}"
  become: yes
  become_user: postgres

- name: Create db user
  postgresql_user:
    state: present
    name: "{{ lookup('env', 'POSTGRES_USER' }}"
    password: "{{ lookup('env', 'POSTGRES_PASSWORD' }}"
  become: yes
  become_user: postgres

- name: Grant db user access to app db
  postgresql_privs:
    type: database
    database: "{{ lookup('env', 'POSTGRES_DB' }}"
    roles: "{{ lookup('env', 'POSTGRES_USER' }}"
    grant_option: no
    privs: all
  become: yes
  become_user: postgres
