apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  annotation: {}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-imdbgraph.vault.azure.net/"
      serviceAccountRef:
        name: workload-identity-sa