---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false
    gateway:
      enabled: true
      # annotations:
      #   cert-manager.io/issuer: selfsigned-issuer
      listeners:
        web:
          port: 80
          protocol: HTTP
        # websecure:
        #   port: 443
        #   protocol: HTTPS
        #   certificateRefs:
        #     - name: imdbgraph-tls
    ports:
      web:
        port: :80
      # websecure:
      #   port: :443
      #   tls:
      #     enabled: true
      # additionalArguments:
      #   - --entryPoints.web.http.redirections.to=websecure
      #   - --entryPoints.web.http.redirections.scheme=https
      #   - --entryPoints.web.http.redirections.permanent=true