- name: Install certbot
  become: true
  snap:
    name:
      - certbot
    classic: true

- name: Link the Certbot command
  become: true
  file:
    src: "/snap/bin/certbot"
    dest: "/usr/bin/certbot"
    state: link

- name: Install certificates
  become: true
  command: "certbot --nginx --non-interactive --agree-tos --email aamini1024@gmail.com --domains {{ hostname }}"
  register: certbot_result
  changed_when:
    - '"Certificate not yet due for renewal" not in certbot_result.stdout'