- name: Setup certbot and certificate renewal
  become: true
  block:
  - name: Install certbot
    snap:
      name: certbot
      classic: true

  - name: Link the Certbot command
    file:
      src: "/snap/bin/certbot"
      dest: "/usr/bin/certbot"
      state: link

  - name: Install certificates
    command: "certbot --nginx --non-interactive --agree-tos --email aamini1024@gmail.com --domains {{ inventory_hostname }}"
    register: certbot_result
    changed_when:
      - '"Certificate not yet due for renewal" not in certbot_result.stdout'