---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: imdbgraph
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-controllers
  path: ./manifests/apps/imdbgraph
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-config
  path: ./manifests/infrastructure/controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1h0m
  retryInterval: 1m
  timeout: 5m
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  path: ./manifests/infrastructure/config/overlays/staging
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1h0m
  retryInterval: 1m
  timeout: 5m
  prune: true