apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-helm-releases
  namespace: flux-system
spec:
  path: ./manifests/infrastructure/helm
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1h0m
  retryInterval: 1m
  timeout: 5m
  prune: true