- name: Install Docker
  block:
    - name: Install Docker from snap
      become: true
      snap:
        name: docker
    # To run Docker without root: https://docs.docker.com/engine/install/linux-postinstall/
    - name: Create docker group
      become: true
      group:
        name: docker
        state: present
    # SSH reset required after user creation: https://stackoverflow.com/a/44753457
    - name: Create docker user
      become: true
      user:
        name: docker
        groups: docker
        append: true
      register: result
    - name: Reset ssh connection to allow user changes to affect 'current login user'
      ansible.builtin.meta: reset_connection

- name: Create data directory
  file:
    name: "/home/{{ ansible_user }}/data"
    state: directory

- name: Login to Docker
  docker_login:
    registry: registry.gitlab.com/imdbgraph/imdbgraph-api
    username: "{{ lookup('env', 'CI_REGISTRY_USER') }}"
    password: "{{ lookup('env', 'CI_REGISTRY_PASSWORD') }}"

- name: Run app container
  docker_container:
    image: "registry.gitlab.com/imdbgraph/imdbgraph-api:main"
    name: imdbgraph-api
    pull: true
    state: started
    network_mode: host
    restart_policy: always
    env:
      DATABASE_HOST: "{{ db_host }}"
      DATABASE_DB: "{{ db_name }}"
      DATABASE_USER: "{{ db_user }}"
      DATABASE_PASSWORD: "{{ db_password }}"
      OMDB_KEY: "{{ omdb_key }}"