---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imdbgraph
  namespace: cert-manager
spec:
  secretName: imdbgraph-tls
  dnsNames:
    - api.staging.imdbgraph.org
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-issuer-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: traefik-gateway
                namespace: traefik
                kind: Gateway