on:
  workflow_call:

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-24.04
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - name: Run ansible script
        run: |
          cd infra/ansible
          ansible-playbook -i staging site.yml