name: "Workflow for Staging Environment"

on:
  pull_request:
    branches: ["main"]

jobs:
  provision:
    uses: ./.github/workflows/infra.yml
    permissions:
      contents: write      # required to merge PRs
      actions: write       # required for plan persistence
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      issues: read         # required to check if PR number is an issue or not
      statuses: write      # required to validate combined PR status
    with:
      environment: staging

  deploy:
    needs: provision
    uses: ./.github/workflows/app.yml
    permissions:
      checks: write
      packages: write
    with:
      environment: staging

