name: "Workflow for imdbgraph-api Staging Environment"

on:
  pull_request:
    branches: ['$default-branch']

jobs:
  provision:
    name: Provision Staging Environment (Terraform)
    runs-on: ubuntu-24.02
    steps:
      - uses: ./.github/workflows/app.yml
        with:
          environment: staging
      - uses: ./.github/workflows/infra.yml
        with:
          environment: staging

