name: "Staging Pipeline"

on:
  pull_request:
    branches: ["main"]

jobs:
  staging-pipeline:
    permissions:
      packages: write
      checks: write
      id-token: write
      contents: read

    uses: ./.github/workflows/pipeline.yml
    with:
      environment: staging
    secrets: inherit
