name: "Staging Pipeline"

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    permissions:
      packages: write
      checks: write
    uses: ./.github/workflows/template-gradle.yml

  provision:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/template-terraform.yml
    with:
      environment: staging
    secrets: inherit

  deploy:
    uses: ./.github/workflows/template-ansible.yml
    needs: [ build, provision ]
    with:
      environment: staging
    secrets: inherit
