name: "Continuous Integration"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write # Required to write docker images to the GitHub Container Registry
      contents: read  # Required to read the source code
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ github.head_ref || github.ref_name }}
      CI_REGISTRY_USER: ${{ github.actor }}
      CI_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Setup Gradle (https://github.com/gradle/actions/tree/main/setup-gradle)
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      # Build + Test
      - name: Test
        run: ./gradlew check
      # Publish (https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages)
      - name: Publish Image
        run: |
          ./gradlew bootBuildImage --publishImage --imageName $IMAGE_NAME