on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  build:
    permissions:
      checks: write
      packages: write
    uses: ./.github/workflows/template-gradle.yml

  provision:
    permissions:
      contents: write      # required to merge PRs
      actions: write       # required for plan persistence
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      issues: read         # required to check if PR number is an issue or not
      statuses: write      # required to validate combined PR status
    uses: ./.github/workflows/template-terraform.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  deploy:
    uses: ./.github/workflows/template-ansible.yml
    needs: [build, provision]
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

